version: "3.1"

services:
  mongo:
    image: mongo:4.2
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./.env
    restart: always
